services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - '9696:9696'
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Etc/UTC' # Set Timezone
    volumes:
      # (Note: Remove the brackets '[]')
      - [/path/to/prowlarr/config]:/config:rw
    restart: unless-stopped
