version: "3"

services:
  sonarr:
    image: "lscr.io/linuxserver/radarr:latest"
    container_name: "radarr"
    restart: "unless-stopped"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC" # Set Timezone
    ports:
      - "7878:7878"
    volumes:
      # (Note: Remove the brackets '[]')
      - "[/path/to/radarr/config]:/config:rw"
      - "[/path/to/downloads]:/downloads:rw" # Optional (For automating downloading torrents)
      - "[/path/to/media/movies]:/media/Shows:ro"
      # If you have more TV Show Directories add them here:
#      - "[/path/to/media/animemovies]:/media/animeshows:ro"
