services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - '8989:8989'
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Etc/UTC' # Set Timezone
    volumes:
      # (Note: Remove the brackets '[]')
      - [/path/to/sonarr/config]:/config:rw
      - [/path/to/downloads]:/downloads:rw # Optional (For automating downloading torrents)
      - [/path/to/media/shows]:/media/Shows:ro
      # If you have more TV Show Directories add them here:
#      - [/path/to/media/animeshows]:/media/animeshows:ro
    restart: unless-stopped
